os: linux
language: C
compiler: gcc
script: make && make test
notifications:
  slack:
    secure: SFwu0gedHYJpvf57C8o65EIstB/VngB8mrj4mQOkB7xujleKATNgraTHGgf6ldsGeKLIdr9iGpOvv5iLNcs3JzrOJNntmpkEmU59d3/5BLcHP90NtNdXCAmSTlVMxmvi2ewnUnTygdPRPFily6TZH63EsVqrCiD+Y8z/fH5JMzPZqZX6BSfrEUtKjychB7XRm/CgZ6a49x71QS5CFGvfc+Ptz0n3f5NgF/qZ7VzGdglisiyAMW3cZJENNuy1Stk9oB+LLl88RnZU9vQin355rf7d5kEVA7pMsKL6pAxjUy3FVZkUz971ECVmu7UoDeVHBnu6jmgmuKs0mLtPXShA9laLNsczCdPiAi24EeDbej33gZL8LP5b13yIW4nt1JnuYO+aeSos4dMTPn7Ua1K8+4Lm2tDQ8uBiX64k3OyE0YvTUKN9khYiDeRwvOWVNB/EB0yBXK73AoCDi8g7s/yzgRTFbdjuTtankIZY5VJnt3ktJ6rOgsZ6c6FRl6fdBG/46EHWZgctjNG70k3dhubnvsL0mweb5foOtbCYmGScHojmeU6zr1XqZrvB+rr4FozyCZnkdnkyAuXp1YpYYZEk2AkRkav+Vn8LyYbVKKJgEAQKPnf5mpYxUdN5kb1bHbj837s44cK4xzs6jwDoQXYQn/dkZgSqfiIbtqXZaDPm+So=
